# Generated by Django 4.2.17 on 2024-12-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_char_count_message_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='total_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='total_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
    ]
