# Generated by Django 4.2.17 on 2024-12-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_channel_total_characters_channel_total_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
    ]
