# Generated by Django 4.2.17 on 2024-12-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_channel_total_messages_discorduser_total_messages'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='api_message_timesta_d1f903_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel'], name='api_message_channel_1c21a7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author'], name='api_message_author__b0e470_idx'),
        ),
    ]
