# Generated by Django 4.2.17 on 2024-12-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_api_message_timesta_d1f903_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='call_ended',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
