# Generated by Django 4.2.17 on 2024-12-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_message_call_ended_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
