# Generated by Django 4.2.17 on 2024-12-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_call_ended_alter_message_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='api_message_timesta_97ab18_idx'),
        ),
    ]
